### ISSUE TITLE
Hamlet Group Image changes

### ISSUE THREAD

**Issue by enterence** [zyxzyx/landing#2]
Hi Mike and Ajay,

Here are the changes that we need to the image slider :
1. Leave the first image (of the polo game).
2. Second one is also ok. leave it.
3. third and 4th images needs to be removed.
4. replace the third image with the following :+1: 
   buffet-315691.jpg (found under hamlet group plc > Indian food from the web
5. Add this image :+1: IMG_3583.JPG & IMG_3577.JPG & IMG_3572.JPG( found under Hamlet Group plc > Images for the site.

**Comment by trevorlazarus** [comment]
@enterence  The images have been changed, closing this issue now.
